@echo off
rem -----------------------------------------------------------------------------
rem Gradle start-up script for Windows
rem
rem Generated by the 'gradle wrapper' task.
rem -----------------------------------------------------------------------------
setlocal
set DIRNAME=%~dp0
set WRAPPER_JAR=%DIRNAME%gradle\wrapper\gradle-wrapper.jar
"%JAVA_HOME%\bin\java" %JAVA_OPTS% -jar "%WRAPPER_JAR%" %*
endlocal
