#!/usr/bin/env sh
##############################################################################
## Gradle start-up script for UN*X
##
## Generated by the 'gradle wrapper' task.
##############################################################################
# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=""

# Add further user-defined JVM options to GRADLE_OPTS
GRADLE_OPTS="${GRADLE_OPTS:-$DEFAULT_JVM_OPTS}"

# Resolve links - $0 may be a softlink
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

PRGDIR=`dirname "$PRG"`

# Determine Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD=java
fi

exec "$JAVACMD" ${GRADLE_OPTS} -jar "$PRGDIR/gradle/wrapper/gradle-wrapper.jar" "$@"
