FROM eclipse-temurin:21-jdk AS build
WORKDIR /home/project
COPY --chown=root:root . .

# Asegura que el wrapper es ejecutable y build con él
RUN chmod +x ./gradlew && ./gradlew clean bootJar --no-daemon

FROM eclipse-temurin:21-jre-jammy
ARG JAR_FILE=build/libs/*.jar
COPY --from=build /home/project/${JAR_FILE} /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]